learning_template/basic_app/urls.py
from django.urls import path
from basic_app import views

#Template Tagging
app_name = 'basic_app'


urlpatterns = [
    path('relative/',views.relative, name = 'relative'),
    path('other/',views.other, name = 'other')
]

learning_template/learning_template/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

learning_template/basic_app/models.py
from django.db import models

# Create your models here.

learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'templates/index.html')


def other(request):
    return render(request,'templates/other.html')

def relative(request):
    return render(request,'templates/relative_template.html')

learning_template/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

learning_template/templates/index.html
<!DOCTYPE html>

{% extends "templates/base.html" %}
    {% block body_block %}

     <h1>It's working, welcome to the home page!</h1>
     

     {% endblock %}

learning_template/templates/other.html
<!DOCTYPE html>

{% extends "templates/base.html" %}
    {% block body_block %}

        <h1>Welcome to the other page</h1>
        

        {% endblock %}
    

learning_template/templates/relative_template.html
<!DOCTYPE html>

{% extends "templates/base.html" %}
    {% block body_block %}

        <h1>Welcome to the relative page!</h1>
        

        {% endblock %}
    